# ==========================================
# Server & Environment Settings
# ==========================================
server.port=${PORT:8080}
spring.devtools.livereload.enabled=false

# ==========================================
# Database Configuration (Render Postgres)
# ==========================================
#prod db config
# internal db url
# jdbc:postgresql://dpg-d8379k3rjlhs73e89qn0-a/wechatdb?sslmode=require
# external db url
# jdbc:postgresql://dpg-d8379k3rjlhs73e89qn0-a.singapore-postgres.render.com/wechatdb?sslmode=require
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# ==========================================
# Google OAuth2 Config
# ==========================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=${RENDER_EXTERNAL_URL}/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub


# ==========================================
# Firebase Configuration
# ==========================================
firebase.config.path=file:///etc/secrets/wechat-ec503-firebase-adminsdk-fbsvc-02a7509602.json
# ==========================================

# ==========================================
# Google OAuth Configuration
# ==========================================
google.oauth.config.path=file:///etc/secrets/client_secret_416052037332-l2blpcf7qklqmtblgham6o10nu3ell7d.apps.googleusercontent.com.json


# GitHub OAuth2 Config
# ==========================================
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email

# ==========================================
# Email Config (SMTP)
# ==========================================
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${SMTP_USERNAME}
#spring.mail.password=${SMTP_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#
## This is the crucial change for Port 587
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.enable=false

google.gmail.client-id=${GMAIL_CLIENT_ID}
google.gmail.client-secret=${GMAIL_CLIENT_SECRET}
google.gmail.refresh-token=${GMAIL_REFRESH_TOKEN}
google.gmail.sender-email=${GMAIL_SENDER_EMAIL}

# ==========================================
# Cloudflare R2 Configuration
# ==========================================
r2.bucket=attachments
r2.endpoint=${R2_ENDPOINT}
r2.public-sub-domain=${R2_PUBLIC_SUB_DOMAIN}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}